module Formulas where

import LPO


p = (Pred "p" [Var "x"])          -- P(X)
q = (Pred "q" [Var "x", Var "y"]) -- Q(X,Y)
r = (Pred "r" [Var "z"])          -- R(Z)
noP = (No p)                      -- ¬P(X)
noQ = (No q)                      -- ¬Q(X,Y)
noR = (No r)                      -- ¬R(Z)

-- And operator
form1   = No (noP)                 -- ¬(¬P(X))
form2   = Y p q                    -- P(X)∧Q(X,Y)
form3   = Y noP q                  -- ¬P(X)∧Q(X,Y)
form4   = Y p noQ                  -- P(X)∧¬Q(X,Y)
form5   = Y noP noQ                -- ¬P(X)∧¬Q(X,Y)
form6   = No (form2)               -- ¬(P(X)∧Q(X,Y))
form7   = No (form3)               -- ¬(¬P(X)∧Q(X,Y))
form8   = No (form4)               -- ¬(P(X)∧¬Q(X,Y))
form9   = No (form5)               -- ¬(¬P(X)∧¬Q(X,Y))

-- OR operator
form10  = O p q                    -- P(X)∨Q(X,Y)
form11  = O noP q                  -- ¬P(X)∨Q(X,Y)
form12  = O p noQ                  -- P(X)∨¬Q(X,Y)
form13  = O noP noQ                -- ¬P(X)∨¬Q(X,Y)
form14  = No (form10)              -- ¬(P(X)∨Q(X,Y))
form15  = No (form11)              -- ¬(¬P(X)∨Q(X,Y))
form16  = No (form12)              -- ¬(P(X)∨¬Q(X,Y))
form17  = No (form13)              -- ¬(¬P(X)∨¬Q(X,Y))

-- Imply operator
form18  = Imp p q                  -- P(X)⊃Q(X,Y)
form19  = Imp noP q                -- ¬P(X)⊃Q(X,Y)
form20  = Imp p noQ                -- P(X)⊃¬Q(X,Y)
form21  = Imp noP noQ              -- ¬P(X)⊃¬Q(X,Y)
form22  = No (form18)              -- ¬(P(X)⊃Q(X,Y))
form23  = No (form19)              -- ¬(¬P(X)⊃Q(X,Y))
form24  = No (form20)              -- ¬(P(X)⊃¬Q(X,Y))
form25  = No (form21)              -- ¬(¬P(X)⊃¬Q(X,Y))

-- For All operator
form26  = A "x" (form1)            -- ∀X.(¬(¬P(X)))
form27  = A "x" (form2)            -- ∀X.(P(X)∧Q(X,Y))
form28  = A "x" (form3)            -- ∀X.(¬P(X)∧Q(X,Y))
form29  = A "x" (form4)            -- ∀X.(P(X)∧¬Q(X,Y))
form30  = A "x" (form5)            -- ∀X.(¬P(X)∧¬Q(X,Y))
form31  = A "x" (form6)            -- ∀X.(¬(P(X)∧Q(X,Y)))
form32  = A "x" (form7)            -- ∀X.(¬(¬P(X)∧Q(X,Y)))
form33  = A "x" (form8)            -- ∀X.(¬(P(X)∧¬Q(X,Y)))
form34  = A "x" (form9)            -- ∀X.(¬(¬P(X)∧¬Q(X,Y)))
form35  = A "x" (form10)           -- ∀X.(P(X)∨Q(X,Y))
form36  = A "x" (form11)           -- ∀X.(¬P(X)∨Q(X,Y))
form37  = A "x" (form12)           -- ∀X.(P(X)∨¬Q(X,Y))
form38  = A "x" (form13)           -- ∀X.(¬P(X)∨¬Q(X,Y))
form39  = A "x" (form14)           -- ∀X.(¬(P(X)∨Q(X,Y)))
form40  = A "x" (form15)           -- ∀X.(¬(¬P(X)∨Q(X,Y)))
form41  = A "x" (form16)           -- ∀X.(¬(P(X)∨¬Q(X,Y)))
form42  = A "x" (form17)           -- ∀X.(¬(¬P(X)∨¬Q(X,Y)))
form43  = A "x" (form18)           -- ∀X.(P(X)⊃Q(X,Y))
form44  = A "x" (form19)           -- ∀X.(¬P(X)⊃Q(X,Y))
form45  = A "x" (form20)           -- ∀X.(P(X)⊃¬Q(X,Y))
form46  = A "x" (form21)           -- ∀X.(¬P(X)⊃¬Q(X,Y))
form47  = A "x" (form22)           -- ∀X.(¬(P(X)⊃Q(X,Y)))
form48  = A "x" (form23)           -- ∀X.(¬(¬P(X)⊃Q(X,Y)))
form49  = A "x" (form24)           -- ∀X.(¬(P(X)⊃¬Q(X,Y)))
form50  = A "x" (form25)           -- ∀X.(¬(¬P(X)⊃¬Q(X,Y)))
form51  = No (form26)              -- ¬(∀X.(¬(¬P(X))))
form52  = No (form27)              -- ¬(∀X.(P(X)∧Q(X,Y)))
form53  = No (form28)              -- ¬(∀X.(¬P(X)∧Q(X,Y)))
form54  = No (form29)              -- ¬(∀X.(P(X)∧¬Q(X,Y)))
form55  = No (form30)              -- ¬(∀X.(¬P(X)∧¬Q(X,Y)))
form56  = No (form31)              -- ¬(∀X.(¬(P(X)∧Q(X,Y))))
form57  = No (form32)              -- ¬(∀X.(¬(¬P(X)∧Q(X,Y))))
form58  = No (form33)              -- ¬(∀X.(¬(P(X)∧¬Q(X,Y))))
form59  = No (form34)              -- ¬(∀X.(¬(¬P(X)∧¬Q(X,Y))))
form60  = No (form35)              -- ¬(∀X.(P(X)∨Q(X,Y)))
form61  = No (form36)              -- ¬(∀X.(¬P(X)∨Q(X,Y)))
form62  = No (form37)              -- ¬(∀X.(P(X)∨¬Q(X,Y)))
form63  = No (form38)              -- ¬(∀X.(¬P(X)∨¬Q(X,Y)))
form64  = No (form39)              -- ¬(∀X.(¬(P(X)∨Q(X,Y))))
form65  = No (form40)              -- ¬(∀X.(¬(¬P(X)∨Q(X,Y))))
form66  = No (form41)              -- ¬(∀X.(¬(P(X)∨¬Q(X,Y))))
form67  = No (form42)              -- ¬(∀X.(¬(¬P(X)∨¬Q(X,Y))))
form68  = No (form43)              -- ¬(∀X.(P(X)⊃Q(X,Y)))
form69  = No (form44)              -- ¬(∀X.(¬P(X)⊃Q(X,Y)))
form70  = No (form45)              -- ¬(∀X.(P(X)⊃¬Q(X,Y)))
form71  = No (form46)              -- ¬(∀X.(¬P(X)⊃¬Q(X,Y)))
form72  = No (form47)              -- ¬(∀X.(¬(P(X)⊃Q(X,Y))))
form73  = No (form48)              -- ¬(∀X.(¬(¬P(X)⊃Q(X,Y))))
form74  = No (form49)              -- ¬(∀X.(¬(P(X)⊃¬Q(X,Y))))
form75  = No (form50)              -- ¬(∀X.(¬(¬P(X)⊃¬Q(X,Y))))

-- Exists operator
form76  = E "x" (form1)            -- ∃X.(¬(¬P(X)))
form77  = E "x" (form2)            -- ∃X.(P(X)∧Q(X,Y))
form78  = E "x" (form3)            -- ∃X.(¬P(X)∧Q(X,Y))
form79  = E "x" (form4)            -- ∃X.(P(X)∧¬Q(X,Y))
form80  = E "x" (form5)            -- ∃X.(¬P(X)∧¬Q(X,Y))
form81  = E "x" (form6)            -- ∃X.(¬(P(X)∧Q(X,Y)))
form82  = E "x" (form7)            -- ∃X.(¬(¬P(X)∧Q(X,Y)))
form83  = E "x" (form8)            -- ∃X.(¬(P(X)∧¬Q(X,Y)))
form84  = E "x" (form9)            -- ∃X.(¬(¬P(X)∧¬Q(X,Y)))
form85  = E "x" (form10)           -- ∃X.(P(X)∨Q(X,Y))
form86  = E "x" (form11)           -- ∃X.(¬P(X)∨Q(X,Y))
form87  = E "x" (form12)           -- ∃X.(P(X)∨¬Q(X,Y))
form88  = E "x" (form13)           -- ∃X.(¬P(X)∨¬Q(X,Y))
form89  = E "x" (form14)           -- ∃X.(¬(P(X)∨Q(X,Y)))
form90  = E "x" (form15)           -- ∃X.(¬(¬P(X)∨Q(X,Y)))
form91  = E "x" (form16)           -- ∃X.(¬(P(X)∨¬Q(X,Y)))
form92  = E "x" (form17)           -- ∃X.(¬(¬P(X)∨¬Q(X,Y)))
form93  = E "x" (form18)           -- ∃X.(P(X)⊃Q(X,Y))
form94  = E "x" (form19)           -- ∃X.(¬P(X)⊃Q(X,Y))
form95  = E "x" (form20)           -- ∃X.(P(X)⊃¬Q(X,Y))
form96  = E "x" (form21)           -- ∃X.(¬P(X)⊃¬Q(X,Y))
form97  = E "x" (form22)           -- ∃X.(¬(P(X)⊃Q(X,Y)))
form98  = E "x" (form23)           -- ∃X.(¬(¬P(X)⊃Q(X,Y)))
form99  = E "x" (form24)           -- ∃X.(¬(P(X)⊃¬Q(X,Y)))
form100 = E "x" (form25)           -- ∃X.(¬(¬P(X)⊃¬Q(X,Y)))
form101 = No (form76)              -- ¬(∃X.(¬(¬P(X))))
form102 = No (form77)              -- ¬(∃X.(P(X)∧Q(X,Y)))
form103 = No (form78)              -- ¬(∃X.(¬P(X)∧Q(X,Y)))
form104 = No (form79)              -- ¬(∃X.(P(X)∧¬Q(X,Y)))
form105 = No (form80)              -- ¬(∃X.(¬P(X)∧¬Q(X,Y)))
form106 = No (form81)              -- ¬(∃X.(¬(P(X)∧Q(X,Y))))
form107 = No (form82)              -- ¬(∃X.(¬(¬P(X)∧Q(X,Y))))
form108 = No (form83)              -- ¬(∃X.(¬(P(X)∧¬Q(X,Y))))
form109 = No (form84)              -- ¬(∃X.(¬(¬P(X)∧¬Q(X,Y))))
form110 = No (form85)              -- ¬(∃X.(P(X)∨Q(X,Y)))
form111 = No (form86)              -- ¬(∃X.(¬P(X)∨Q(X,Y)))
form112 = No (form87)              -- ¬(∃X.(P(X)∨¬Q(X,Y)))
form113 = No (form88)              -- ¬(∃X.(¬P(X)∨¬Q(X,Y)))
form114 = No (form89)              -- ¬(∃X.(¬(P(X)∨Q(X,Y))))
form115 = No (form90)              -- ¬(∃X.(¬(¬P(X)∨Q(X,Y))))
form116 = No (form91)              -- ¬(∃X.(¬(P(X)∨¬Q(X,Y))))
form117 = No (form92)              -- ¬(∃X.(¬(¬P(X)∨¬Q(X,Y))))
form118 = No (form93)              -- ¬(∃X.(P(X)⊃Q(X,Y)))
form119 = No (form94)              -- ¬(∃X.(¬P(X)⊃Q(X,Y)))
form120 = No (form95)              -- ¬(∃X.(P(X)⊃¬Q(X,Y)))
form121 = No (form96)              -- ¬(∃X.(¬P(X)⊃¬Q(X,Y)))
form122 = No (form97)              -- ¬(∃X.(¬(P(X)⊃Q(X,Y))))
form123 = No (form98)              -- ¬(∃X.(¬(¬P(X)⊃Q(X,Y))))
form124 = No (form99)              -- ¬(∃X.(¬(P(X)⊃¬Q(X,Y))))
form125 = No (form100)             -- ¬(∃X.(¬(¬P(X)⊃¬Q(X,Y))))

-- forAll & Exits operators
form126 = A "Y" (form77)           -- ∀Y.(∃X.(P(X)∧Q(X,Y))) 
form127 = A "Y" (form85)           -- ∀Y.(∃X.(P(X)∨Q(X,Y))) 
form128 = A "Y" (form93)           -- ∀Y.(∃X.(P(X)⊃Q(X,Y))) 
form129 = A "y" (form27)           -- ∀Y.(∀X.(P(X)∧Q(X,Y)))
form130 = A "Y" (form102)          -- ∀Y.(¬(∃X.(P(X)∧Q(X,Y)))) 
form131 = A "Y" (form110)          -- ∀Y.(¬(∃X.(P(X)∨Q(X,Y)))) 
form132 = A "Y" (form118)          -- ∀Y.(¬(∃X.(P(X)⊃Q(X,Y)))) 
form133 = A "y" (form52)           -- ∀Y.(¬(∀X.(P(X)∧Q(X,Y))))
form134 = E "Y" (form27)           -- ∃Y.(∀X.(P(X)∧Q(X,Y))) 
form135 = E "Y" (form35)           -- ∃Y.(∀X.(P(X)∨Q(X,Y))) 
form136 = E "Y" (form43)           -- ∃Y.(∀X.(P(X)⊃Q(X,Y))) 
form137 = E "y" (form77)           -- ∃Y.(∃X.(P(X)∧Q(X,Y)))
form138 = E "Y" (form52)           -- ∃Y.(¬(∀X.(P(X)∧Q(X,Y)))) 
form139 = E "Y" (form60)           -- ∃Y.(¬(∀X.(P(X)∨Q(X,Y)))) 
form140 = E "Y" (form68)           -- ∃Y.(¬(∀X.(P(X)⊃Q(X,Y)))) 
form141 = E "y" (form102)          -- ∃Y.(¬(∃X.(P(X)∧Q(X,Y))))


-- Asignaciones
asignacion1::Asignacion Int
asignacion1 "X" = 0
asignacion1 "Y" = 1
asignacion1 "Z" = 2

asignacion2::Asignacion Int
asignacion2 "X" = 10
asignacion2 "Y" = 10
asignacion2 "Z" = 2

-- Expresiones
term1 = Func "suma" [Func "suc" [Var "X"], Var "Y"] -- suma(suc(x),y)
term2 = Func "producto" [Func "invertir" [Var "Y"], Var "Z", Var "Z"] -- producto(invertir(y), z, z)
